version: '3'
services:

  # #################################
  # # wishlist: The wishlist microservice
  # #################################
  # wishlist:
  #   image: kuehlapis/wishlist:1.0  
  #   restart: always
  #   environment:
  #     dbURL: http://wishlist:5001/wishlist
  #   ports:
  #     - "8081:5000"



  #################################
  # send_email: The notification microservice
  #################################
  send_email:
    image: caifan4eva/send_email:1.0
    restart: always
    build: .
    ports:
      - "8082:5000"
